name: justwish

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - users-api
      - seq

  users-api: 
    build:
      context: ./backend/Justwish.Users/
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5001
      ConnectionStrings:RedisConnection: redis:6379
      ConnectionStrings:ApplicationConnection: Host=postgres;Port=5432;Username=postgres;Password=postgres;Database=Users;
    depends_on:
      - redis
      - seq

  seq:
    image: datalust/seq
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq_data:/data

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
  
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Users
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
volumes:
  redis-data:
  postgres-data:
  seq_data: